import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./../globals.css";
import Header from "@/components/common/Header";
import Footer from "@/components/common/Footer";

const inter = Roboto({ weight: ["300", "400","500", "700"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gray-Charcoal`}>
        <Header/>
      {children}
      <Footer/>
      </body>
    </html>
  );
}
