import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./../globals.css";

import Footer from "@/components/shared/Footer";
import Navbar from "@/components/shared/Navbar";
import Header from "@/components/shared/Header";

const inter = Roboto({ weight: ["300", "400","500", "700"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gray-Charcoal`}>
        <Header/>
        <Navbar/>
      {children}
      <Footer/>
      </body>
    </html>
  );
}
